// Mirrors backend/app/campus/departments.json. The browser uses this to label
// saved course codes and read-only SAIS department data without another request.
type DepartmentLabel = { abbreviation: string; tr: string; en: string };

const DEPARTMENTS: Record<string, DepartmentLabel> = {
  "120": { abbreviation: "ARCH", tr: "Mimarlık", en: "Architecture" },
  "121": { abbreviation: "CRP", tr: "Şehir ve Bölge Planlama", en: "City and Regional Planning" },
  "125": { abbreviation: "ID", tr: "Endüstriyel Tasarım", en: "Industrial Design" },
  "219": { abbreviation: "GENE", tr: "Moleküler Biyoloji ve Genetik", en: "Molecular Biology and Genetics" },
  "230": { abbreviation: "PHYS", tr: "Fizik", en: "Physics" },
  "232": { abbreviation: "SOC", tr: "Sosyoloji", en: "Sociology" },
  "233": { abbreviation: "PSY", tr: "Psikoloji", en: "Psychology" },
  "234": { abbreviation: "CHEM", tr: "Kimya", en: "Chemistry" },
  "236": { abbreviation: "MATH", tr: "Matematik", en: "Mathematics" },
  "238": { abbreviation: "BIOL", tr: "Biyoloji", en: "Biology" },
  "240": { abbreviation: "HIST", tr: "Tarih", en: "History" },
  "241": { abbreviation: "PHIL", tr: "Felsefe", en: "Philosophy" },
  "246": { abbreviation: "STAT", tr: "İstatistik", en: "Statistics" },
  "310": { abbreviation: "ADM", tr: "Siyaset Bilimi ve Kamu Yönetimi", en: "Political Science and Public Adm." },
  "311": { abbreviation: "ECON", tr: "İktisat", en: "Economics" },
  "312": { abbreviation: "BA", tr: "İşletme", en: "Business Administration" },
  "314": { abbreviation: "IR", tr: "Uluslararası İlişkiler", en: "International Relations" },
  "401": { abbreviation: "", tr: "Temel Eğitim", en: "Elementary and Early Childhood Education" },
  "410": { abbreviation: "", tr: "İlköğretim", en: "Elementary Education" },
  "411": { abbreviation: "ECE", tr: "Okul Öncesi Öğretmenliği", en: "Early Childhood Education" },
  "412": { abbreviation: "ESME", tr: "Fen Bilgisi Öğretmenliği", en: "Elementary Science Education" },
  "413": { abbreviation: "EME", tr: "İlköğretim Matematik Öğretmenliği", en: "Elementary Mathematics Educ." },
  "420": { abbreviation: "", tr: "Ortaöğretim Fen ve Matematik Alan.Eğitimi", en: "Secondary Science and Mathematics Educ." },
  "421": { abbreviation: "PHYE", tr: "Fizik Öğretmenliği", en: "Physics Education" },
  "422": { abbreviation: "CHME", tr: "Kimya Öğretmenliği", en: "Chemistry Education" },
  "423": { abbreviation: "MATE", tr: "Matematik Öğretmenliği", en: "Mathematics Education" },
  "430": { abbreviation: "CEIT", tr: "Bilgisayar ve Öğretim Teknolojileri Eğitimi", en: "Computer Education and Instructional Technology" },
  "450": { abbreviation: "FLE", tr: "İngilizce Öğretmenliği", en: "Foreign Language Education" },
  "453": { abbreviation: "PHED", tr: "Beden Eğitimi ve Spor", en: "Physical Education and Sports" },
  "454": { abbreviation: "EDS", tr: "Eğitim Bilimleri", en: "Educational Sciences" },
  "459": { abbreviation: "", tr: "Biyoloji Öğretmenliği", en: "Biology Education" },
  "460": { abbreviation: "", tr: "Matematik ve Fen Bilimleri Eğitimi", en: "Mathematics and Science Education" },
  "560": { abbreviation: "ENVE", tr: "Çevre Mühendisliği", en: "Environmental Engineering" },
  "561": { abbreviation: "ES", tr: "Mühendislik Bilimleri", en: "Engineering Sciences" },
  "562": { abbreviation: "CE", tr: "İnşaat Mühendisliği", en: "Civil Engineering" },
  "563": { abbreviation: "CHE", tr: "Kimya Mühendisliği", en: "Chemical Engineering" },
  "564": { abbreviation: "GEOE", tr: "Jeoloji Mühendisliği", en: "Geological Engineering" },
  "565": { abbreviation: "MINE", tr: "Maden Mühendisliği", en: "Mining Engineering" },
  "566": { abbreviation: "PETE", tr: "Petrol ve Doğal Gaz Mühendisliği", en: "Petroleum and Natural Gas Engineering" },
  "567": { abbreviation: "EE", tr: "Elektrik ve Elektronik Mühendisliği", en: "Electrical and Electronics Engineering" },
  "568": { abbreviation: "IE", tr: "Endüstri Mühendisliği", en: "Industrial Engineering" },
  "569": { abbreviation: "ME", tr: "Makina Mühendisliği", en: "Mechanical Engineering" },
  "570": { abbreviation: "METE", tr: "Metalurji ve Malzeme Mühendisliği", en: "Metallurgical and Materials Engineering" },
  "571": { abbreviation: "CENG", tr: "Bilgisayar Mühendisliği", en: "Computer Engineering" },
  "572": { abbreviation: "AEE", tr: "Havacılık ve Uzay Mühendisliği", en: "Aerospace Engineering" },
  "573": { abbreviation: "FDE", tr: "Gıda Mühendisliği", en: "Food Engineering" },
  "602": { abbreviation: "", tr: "Modern Diller (Arapça)", en: "Modern Languages (Arabic)" },
  "603": { abbreviation: "FREN", tr: "Modern Diller (Fransızca)", en: "Modern Languages (French)" },
  "604": { abbreviation: "GERM", tr: "Modern Diller (Almanca)", en: "Modern Languages (German)" },
  "605": { abbreviation: "JA", tr: "Modern Diller (Japonca)", en: "Modern Languages (Japanese)" },
  "606": { abbreviation: "ITAL", tr: "Modern Diller (İtalyanca)", en: "Modern Languages (Italian)" },
  "607": { abbreviation: "RUS", tr: "Modern Diller (Rusça)", en: "Modern Languages (Russian)" },
  "608": { abbreviation: "SPAN", tr: "Modern Diller (İspanyolca)", en: "Modern Languages (Spanish)" },
  "609": { abbreviation: "HEB", tr: "Modern Diller (İbranice)", en: "Modern Languages (Hebrew)" },
  "610": { abbreviation: "GRE", tr: "Modern Diller (Yunanca)", en: "Modern Language (Greek)" },
  "611": { abbreviation: "CHN", tr: "Modern Diller (Çince)", en: "Modern Languages (Chinese)" },
  "612": { abbreviation: "PERS", tr: "Modern Diller (Farsça)", en: "Modern Languages (Persian)" },
  "613": { abbreviation: "", tr: "Modern Diller (Korece)", en: "Modern Languages (Korean)" },
  "629": { abbreviation: "", tr: "Modern Diller (Yabancılar için Türk Dili)", en: "Modern Languages (Turkish as a Foreign Languages)" },
  "639": { abbreviation: "ENG", tr: "Modern Diller (İngilizce)", en: "Modern Languages (English)" },
  "642": { abbreviation: "TURK", tr: "Türk Dili", en: "Turkish Language" },
  "643": { abbreviation: "", tr: "Müzik ve Güzel Sanatlar", en: "Music and Fine Arts" },
  "644": { abbreviation: "", tr: "Müzik ve Güzel Sanatlar", en: "Music and Fine Arts" },
  "651": { abbreviation: "THEA", tr: "Müzik ve Güzel Sanatlar", en: "Music and Fine Arts" },
  "682": { abbreviation: "", tr: "Müzik ve Güzel Sanatlar", en: "Music and Fine Arts" },
  "790": { abbreviation: "", tr: "Meslek Yüksekokulu", en: "Tech. Voc.School" },
  "791": { abbreviation: "", tr: "Endüstriyel Otomasyon", en: "Industrial Automation" },
  "792": { abbreviation: "", tr: "Kaynak Teknolojisi", en: "Welding Technology" },
  "795": { abbreviation: "", tr: "Meslek Yüksekokulu", en: "Meslek Yüksekokulu" },
  "796": { abbreviation: "", tr: "Gıda Teknolojisi", en: "Food Technology" },
  "797": { abbreviation: "", tr: "Elektrik", en: "Elektrik" },
  "798": { abbreviation: "", tr: "Elektronik Teknolojisi", en: "Elektronik Teknolojisi" },
  "799": { abbreviation: "", tr: "Endüstriyel Otomasyon", en: "Endüstriyel Otomasyon" },
  "800": { abbreviation: "", tr: "Sosyal Bilimler Enstitüsü", en: "Grad.Institute Social Sciences" },
  "801": { abbreviation: "", tr: "Mimarlık Tarihi", en: "History of Architecture" },
  "810": { abbreviation: "", tr: "Toplumsal Cinsiyet ve Kadın Çalışmaları", en: "Gender&Women Studies" },
  "811": { abbreviation: "", tr: "Kentsel Politika Planlaması ve Yerel Yönetimler", en: "Urban Policy Planning and Local Governments" },
  "814": { abbreviation: "", tr: "Yerleşim Arkeolojisi", en: "Settlement Archaeology" },
  "815": { abbreviation: "", tr: "Bölge Çalışmaları", en: "Area Studies" },
  "816": { abbreviation: "", tr: "Medya ve Kültürel Çalışmaları", en: "Media and Cultural Studies" },
  "817": { abbreviation: "", tr: "Aile Psikolojisi", en: "Family Psychology" },
  "820": { abbreviation: "", tr: "İngiliz Dili Öğretimi", en: "English Language Teaching" },
  "821": { abbreviation: "", tr: "İngiliz Edebiyatı", en: "English Literature" },
  "822": { abbreviation: "", tr: "İlköğretim Fen ve Matematik Eğitimi", en: "Elementary Science and Math. E." },
  "823": { abbreviation: "", tr: "Rehberlik ve Psikolojik Danışmanlık", en: "Guidance and Psychological Counseling" },
  "824": { abbreviation: "", tr: "Eğitim Yönetimi ve Planlaması", en: "Educational Administration and Planning" },
  "825": { abbreviation: "", tr: "Eğitim Programları ve Öğretim", en: "Curriculum and Instruction" },
  "826": { abbreviation: "", tr: "Matematik Eğitimi", en: "Mathematics Education" },
  "827": { abbreviation: "", tr: "Fen Bilimleri Eğitimi", en: "Science Education" },
  "830": { abbreviation: "", tr: "Endüstri ve Örgüt Psikolojisi", en: "Industrial and Organizational Psychology" },
  "831": { abbreviation: "", tr: "Bilim ve Teknoloji Politikası Çalışmaları", en: "Science and Technology Policy Studies" },
  "832": { abbreviation: "", tr: "Orta Doğu Araştırmaları", en: "Middle East Studies" },
  "833": { abbreviation: "", tr: "Avrupa Çalışmaları", en: "European Studies" },
  "834": { abbreviation: "", tr: "Eğtimde İnsan Kaynaklarını Geliştirme", en: "Human Resources Development In Education" },
  "835": { abbreviation: "", tr: "Avrasya Çalışmaları", en: "Eurasian Studies" },
  "836": { abbreviation: "", tr: "Uygulamalı Etik", en: "Applied Ethics" },
  "837": { abbreviation: "", tr: "Yöneticiler için İşletme", en: "Executive Master of Business Administration" },
  "838": { abbreviation: "", tr: "Avrupa Bütünleşmesi", en: "European Integration" },
  "839": { abbreviation: "", tr: "Sosyal Politika", en: "Social Policy" },
  "840": { abbreviation: "", tr: "Sosyal Antropoloji", en: "Social Anthropology" },
  "842": { abbreviation: "", tr: "Asya Çalışmaları", en: "Asian Studies" },
  "843": { abbreviation: "", tr: "Latin ve Kuzey Amerika Çalışmaları", en: "Latin and North American Studies" },
  "844": { abbreviation: "", tr: "Klinik Psikoloji", en: "Clinical Psychology" },
  "852": { abbreviation: "", tr: "Bölge Planlama", en: "Regional Planning" },
  "853": { abbreviation: "", tr: "Şehir Planlama", en: "City Planning" },
  "854": { abbreviation: "", tr: "Yapı Bilimleri", en: "Building Science" },
  "855": { abbreviation: "", tr: "Kentsel Tasarım", en: "Urban Design" },
  "856": { abbreviation: "", tr: "Kültürel Mirası Koruma Programı", en: "Graduate Program in Conservation of Cultural Heritage" },
  "860": { abbreviation: "", tr: "Biyokimya", en: "Biochemistry" },
  "861": { abbreviation: "", tr: "Biyoteknoloji", en: "Biotechnology" },
  "862": { abbreviation: "", tr: "Polimer Bilim ve Teknolojisi", en: "Polymer Science and Technology" },
  "863": { abbreviation: "", tr: "Arkeometri", en: "Archaeometry" },
  "864": { abbreviation: "", tr: "Astrofizik", en: "Astrophysics" },
  "865": { abbreviation: "", tr: "Jeodezi ve Coğrafi Bilgi Teknolojileri", en: "Geodetic and Geographical Information Technologies" },
  "866": { abbreviation: "", tr: "Mühendislik Yönetimi", en: "Engineering Management" },
  "867": { abbreviation: "", tr: "Yazılım Mühendisliği", en: "Software Engineering" },
  "868": { abbreviation: "", tr: "Yapı Mekaniği", en: "Structural Mechanics" },
  "869": { abbreviation: "", tr: "Hidrosistem Mühendisliği", en: "Hydrosystems Engineering" },
  "870": { abbreviation: "", tr: "Çimento Mühendisliği", en: "Cement Engineering" },
  "871": { abbreviation: "", tr: "Mikro ve Nanoteknoloji", en: "Micro and Nanotechnology" },
  "872": { abbreviation: "", tr: "Biyomedikal Mühendisliği", en: "Biomedical Engineering" },
  "873": { abbreviation: "", tr: "Deprem Çalışmaları", en: "Earthquake Studies" },
  "874": { abbreviation: "", tr: "Yer Sistem Bilimleri", en: "Earth System Science" },
  "876": { abbreviation: "", tr: "Mekanik Tasarım ve İmalat", en: "Mechanical Design and Manufacturing" },
  "877": { abbreviation: "OHS", tr: "İş Sağlığı ve Güvenliği", en: "Occupational Health and Safety" },
  "878": { abbreviation: "", tr: "Nörobilim ve Nöroteknoloji", en: "Neuroscience and Neurotechnology" },
  "880": { abbreviation: "", tr: "Yöneylem Araştırması", en: "Operational Research" },
  "884": { abbreviation: "", tr: "Çevre Yönetimi", en: "Environmental Management" },
  "885": { abbreviation: "", tr: "Robotik", en: "Robotics" },
  "886": { abbreviation: "", tr: "Veri ve Karar Bilimleri", en: "Data and Decision Sciences" },
  "887": { abbreviation: "", tr: "Yapay Zeka Mühendisliği", en: "Artificial Intelligence Engineering" },
  "901": { abbreviation: "", tr: "Bilişim Sistemleri", en: "Information Systems" },
  "902": { abbreviation: "", tr: "Bilişsel Bilimler", en: "Cognitive Sciences" },
  "903": { abbreviation: "", tr: "Modelleme Ve Simulasyon", en: "Modelling And Simulation" },
  "904": { abbreviation: "", tr: "Internet Üzerinden Bilişim", en: "Informatics Online" },
  "905": { abbreviation: "", tr: "Yazılım Yönetimi", en: "Software Management" },
  "906": { abbreviation: "", tr: "Tıp Bilişimi", en: "Medical Informatics" },
  "908": { abbreviation: "", tr: "Biyoenformatik", en: "Bioinformatics" },
  "909": { abbreviation: "MMI", tr: "Çokluortam Bilişimi", en: "Multimedia Informatics" },
  "910": { abbreviation: "", tr: "Siber Güvenlik", en: "Cyber Security" },
  "911": { abbreviation: "", tr: "Veri Bilişimi", en: "Data Informatics" },
  "950": { abbreviation: "", tr: "Deniz Bilimleri Enstitüsü", en: "Graduate School of Marine Sciences" },
  "951": { abbreviation: "", tr: "Fiziksel Oşinografi", en: "Phys. Oceanography" },
  "952": { abbreviation: "", tr: "Kimyasal Oşinografi", en: "Chemical Oceanography" },
  "953": { abbreviation: "", tr: "Deniz Jeolojisi ve Jeofiziği", en: "Marine Geology and Geophysics" },
  "954": { abbreviation: "", tr: "Deniz Biyolojisi ve Balıkçılığı", en: "Marine Biology and Fisheries" },
  "956": { abbreviation: "", tr: "Deniz Bilim (Oşinografi)", en: "Oceanography" },
  "970": { abbreviation: "", tr: "Uygulamalı Matematik Enstitüsü", en: "Institute Of Applied Mathematics" },
  "971": { abbreviation: "", tr: "Kriptografi", en: "Cryptography" },
  "972": { abbreviation: "", tr: "Bilimsel Hesaplama", en: "Scientific Computing Program" },
  "973": { abbreviation: "FM", tr: "Finansal Matematik", en: "Financial Mathematics" },
  "974": { abbreviation: "", tr: "Finansal Matematik: Hayat Sigortası Opsiyonu", en: "Financial Mathematics: Life Insurance Option" },
  "976": { abbreviation: "", tr: "Aktüerya Bilimleri", en: "Actuarial Science" },
};

export function formatMetuCourseCode(value: string) {
  const normalized = value.trim().toUpperCase();
  if (!/^\d{7}$/.test(normalized)) return normalized;
  const abbreviation = DEPARTMENTS[normalized.slice(0, 3)]?.abbreviation;
  if (!abbreviation) return normalized;
  const number = normalized.slice(3).replace(/^0+/, "") || "0";
  return `${abbreviation} ${number}`;
}

export function formatMetuDepartment(code: string | null, fallback: string | null, locale: "tr" | "en") {
  const department = code ? DEPARTMENTS[code] : undefined;
  if (!department) return fallback || "—";
  const name = department[locale] || fallback || code;
  return department.abbreviation ? `${department.abbreviation} — ${name}` : name;
}
